spring:
  application:
    name: config-properties-ecommercefinal
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jfernandez97/config-properties-ecommercefinal
server:
  port: 8888
